### ISSUE TITLE
[FEATURE] Documentation: Add a link to AdiBags

### ISSUE THREAD

**Issue by SpareSimian** [AvyAddons/AdiBags_Bound#3]
It would be useful to have a link in the Readme back to the [AdiBags addon](https://github.com/AdiAddons/AdiBags) so newcomers will know what this is for. 

Also, kudos to your cleanup! I'd been patching the old code but I really love what you've done with the place. The new code looks quite nice. And the GitHub release packaging means I can use Ajour to update it. 

Suggestion: Request a link to your addon in the AdiBags Readme, in the Modules section.

**Comment by lucasvienna** [comment]
Thanks mate! It was a bit of learn as you go, and it's improved a lot since I started tinkering with it :)

Updated the README, points out the plugin nature of this addon and links to the base AdiBags, see [922056f](https://github.com/AvyAddons/AdiBags_Bound/commit/922056fc6ac65627180ff0d8e8d17355f42ae32b)
